name       : libnftnl
version    : 1.1.9
release    : 2
source     :
    - https://www.netfilter.org/projects/libnftnl/files/libnftnl-1.1.9.tar.bz2 : e9b21a6f9a41f9e72aff696cc842e4a9a78ec8d281aec188f3e2b7a21db94b9a
license    : GPL-2.0-or-later
component  : programming.library
homepage   : https://www.netfilter.org/projects/libnftnl/
summary    : Netfilter library providing interface to the nf_tables subsystem
description: |
    libnftnl is a userspace library providing a low-level netlink programming interface to the in-kernel nf_tables subsystem.
builddeps  :
    - pkgconfig32(libmnl)
emul32     : yes
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
