name       : libnftnl
version    : 1.1.1
release    : 1
source     :
    - https://netfilter.org/projects/libnftnl/files/libnftnl-1.1.1.tar.bz2 : 5d6a65413f27ec635eedf6aba033f7cf671d462a2afeacc562ba96b19893aff2
license    : GPL-2.0-or-later
component  : programming.library
summary    : Netfilter library providing interface to the nf_tables subsystem
description: |
    A library for low-level interaction with nftables Netlink's API over libmnl.
builddeps  :
    - pkgconfig32(jansson)
    - pkgconfig32(libmnl)
emul32     : yes
setup      : |
    %configure --with-json-parsing
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
