name       : libnftnl
version    : 1.2.5
release    : 3
source     :
    - https://www.netfilter.org/projects/libnftnl/files/libnftnl-1.2.5.tar.xz : 966de0a8120c8a53db859889749368bfb2cba0c4f0b4c1a30d264eccc45f1226
license    : GPL-2.0-or-later
component  : programming.library
homepage   : https://www.netfilter.org/projects/libnftnl/
summary    : Netfilter library providing interface to the nf_tables subsystem
description: |
    libnftnl is a userspace library providing a low-level netlink programming interface to the in-kernel nf_tables subsystem.
builddeps  :
    - pkgconfig32(libmnl)
emul32     : yes
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
